// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO6i5jCJhOPa3UGn4lzWp-q-uBUP8YAuY',
    appId: '1:460982484609:web:2fb42e31c4d94b5bd8d780',
    messagingSenderId: '460982484609',
    projectId: 'eclipsis-4d01f',
    authDomain: 'eclipsis-4d01f.firebaseapp.com',
    storageBucket: 'eclipsis-4d01f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKDu_jA4gsxlrxkAfBDh9I4rhqzI3D_IQ',
    appId: '1:460982484609:android:5b28fd502c945679d8d780',
    messagingSenderId: '460982484609',
    projectId: 'eclipsis-4d01f',
    storageBucket: 'eclipsis-4d01f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwaH-ruAOz4KqzdvDRtRcqtfUPztXn9ss',
    appId: '1:460982484609:ios:f4aa9f7da6da2eabd8d780',
    messagingSenderId: '460982484609',
    projectId: 'eclipsis-4d01f',
    storageBucket: 'eclipsis-4d01f.appspot.com',
    iosClientId: '460982484609-3uc2022vcjodf1theil4qdmc3lnmo8t7.apps.googleusercontent.com',
    iosBundleId: 'com.example.eclipsis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwaH-ruAOz4KqzdvDRtRcqtfUPztXn9ss',
    appId: '1:460982484609:ios:bf3738833440aae3d8d780',
    messagingSenderId: '460982484609',
    projectId: 'eclipsis-4d01f',
    storageBucket: 'eclipsis-4d01f.appspot.com',
    iosClientId: '460982484609-ca95pkm4cirrotpbo1uu7m890b4vp4bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.eclipsis.RunnerTests',
  );
}
